#!/bin/bash

echo "Updating system packages..."
sudo yum update -y || sudo apt update -y

echo "Installing curl..."
sudo yum install -y curl || sudo apt install -y curl

echo "Downloading Docker Compose..."
sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose

echo "Giving execute permission..."
sudo chmod +x /usr/local/bin/docker-compose

echo "Creating symbolic link..."
sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose

echo "Checking Docker Compose version..."
docker-compose --version

echo "Docker Compose installed successfully!"
