#!/bin/bash

# Update system
sudo dnf update -y

# Install Java 17
sudo dnf install java-17-amazon-corretto -y

# Add Jenkins repository
sudo wget -O /etc/yum.repos.d/jenkins.repo \
https://pkg.jenkins.io/redhat-stable/jenkins.repo

# Import Jenkins GPG key
sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key

# Install Jenkins
sudo dnf install jenkins -y

# Reload systemd
sudo systemctl daemon-reload

# Start Jenkins
sudo systemctl start jenkins

# Enable Jenkins at boot
sudo systemctl enable jenkins

# Show status
sudo systemctl status jenkins

# Show initial admin password
echo "Jenkins Initial Admin Password:"
sudo cat /var/lib/jenkins/secrets/initialAdminPassword
